### ISSUE TITLE
HACS support

### ISSUE THREAD

**Issue by syphernl** [eelcohn/home-assistant-rdw#12] opened 2020-02-26 12:54 UTC
Could you please add support for HACS? That would make installing / upgrading a lot easier.

**Comment by eelcohn** [comment] 2020-02-27 11:08
Thanks, I'm aware that the HACS support feature is requested by some of the users, and that it would make installing and upgrading a lot easier. I'm currently working on a major update of the RDW platform which I ultimately want to push to the official Home Assistant Core repository. Therefore I'm not really putting effort in HACS support because I want to push RDW to the main repository.

**Comment by eelcohn** [comment] 2020-02-27 11:08
Duplicate of #2

**Closed as completed by eelcohn** 2020-02-27 11:08 UTC
